version: "3.9"
services:
    mysql-server:
        container_name: mysql1
        hostname: mysql1
        image: mysql/mysql-server:latest
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: 'Root2022'
          MYSQL USER: 'admin'
          MYSQL PASSWORD: 'Root2022'
        ports:
          - '3305:3306'
        expose:
          - '3305'
        volumes:
          - '/home/ada/ftp/mysql:/var/mysql'
        networks:
          - mysql1-net

networks:
  mysql1-net:
        name: mysql1-network
