version: "3"
services:
    oracle-db:
        container_name: oracle1
        hostname: oracle1
        image: oracleinanutshell/oracle-xe-11g:latest
        restart: always
        ports:
          - '5500:5500'
          - '1521:1521'
          - '8181:8080'
        volumes:
          - '/home/ada/ftp/oracle:/var/oracle'
        networks:
          - oracle1-net
        environment:
          - ORACLE_ENABLE_XDB=true
          - ORACLE_DISABLE_ASYNCH_IO=true
          - ORACLE_ALLOW_REMOTE=true

networks:
  oracle1-net:
        name: oracle1-network
        
#https://hub.docker.com/r/oracleinanutshell/oracle-xe-11g
